title: "Modo Tab Mount"
description: "Smart in-wall tablet mount with charger and optional ESP32 integration"
remote_theme: pages-themes/minimal@v0.2.0

# Navigation menu
header_pages:
  - index.md
  - about.md
  - installation.md
  - pcb.md
  - shop.md
