title: "Modo Tab Mount"
[//]: description: "Smart in-wall tablet mount with charger and optional ESP32 integration"
logo: docs/images/mtm_animation_2.gif
theme: jekyll-theme-minimal

# Navigation menu
header_pages:
  - index.md
  - about.md
  - installation.md
  - pcb.md
  - shop.md
