title: "Modo Tab Mount"
logo: /images/mtm_animation_2.gif
description: <p>Sleek, minimalist tablet mount for standard EU wall boxes — strong magnetic docking, integrated 5 V power supply with ESP32-C3/ESPHome control, optional addressable LEDs, Bluetooth proxy, and support for additional sensors. Seamless Home Assistant integration</p>
theme: jekyll-theme-minimal
