title: "Modo Tab Mount"
logo: /images/mtm_animation_2.gif
description: <p>Sleek magnetic tablet mount with a smart ESP32-C3/ESPHome power supply, designed for seamless Home Assistant integration. Fits standard EU wall boxes.</p>
theme: jekyll-theme-minimal
