title: "Modo Tab Mount"
description: "Smart in-wall tablet mount with charger and optional ESP32 integration"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Navigation menu
header_pages:
  - index.md
  - about.md
  - installation.md
  - pcb.md
  - shop.md
